# src/research_crew/config/tasks.yaml
research_task:
  description: >
    对 {topic} 进行深入研究，重点涵盖：
    1. 关键概念和定义
    2. 历史发展与最新趋势
    3. 主要挑战与机遇
    4. 典型应用或案例研究
    5. 未来前景与潜在发展

    请确保以结构化格式整理你的发现，并使用清晰的章节。
  expected_output: >
    一份全面的研究文档，带有条理清晰的章节，
    覆盖 {topic} 的所有要求方面。相关处请给出
    具体事实、数据与示例。
  agent: researcher

analysis_task:
  description: >
    分析研究结果并撰写关于 {topic} 的综合报告。
    报告应当：
    1. 以执行摘要开篇
    2. 汇总所有关键研究信息
    3. 对趋势和模式进行深入分析
    4. 提出建议或未来考虑方向
    5. 采用专业、易读的格式，带有清晰标题
  expected_output: >
    一份完善、专业的 {topic} 报告，呈现研究结果并
    添加深入分析与洞见。报告应包含执行摘要、主体
    各章节及结论，结构清晰。
  agent: analyst
  context:
    - research_task
  output_file: output/report.md
